version: "3.7"
services:
  xyhelper-web:
    image: xyhelper/xyhelper-web
    container_name: xyhelper-web
    restart: always
    ports:
      - 8888:8080
    environment:
      AUTH_SECRET_KEY: 123456